name: 'binance_analytics'
version: '1.0.0'

profile: 'binance_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  binance_analytics:
    staging:
      +materialized: view
      +schema: staging
    mart:
      +materialized: table
      +schema: mart